DB:
TiDB_DSN: park_info:DEkcEu0@tcp(116.62.132.145:4000)/park_info?charset=utf8&parseTime=true&loc=Local
OLDTiDB_DSN: config:RmUyNLd95sZr1fcbouRxLXuKa@tcp(116.62.132.145:4000)/config_cloud?charset=utf8
REDIS:
  HOST: 114.115.130.182:16379
  PWD: frm
MQ:
  MQ_DSN: amqp://guest:guest@116.62.132.145:5672
PIGEON:
  ADDR: http://116.62.132.145:9130
  USER: p
  PWD: mjfdRMMhEvb43B8HQp6N9Q7r4KuEQg3pOdN
SERVER:
  BIND_ADDRESS: 0.0.0.0:8081
  MODE: dev
  LOG: ./logs/ParkInfo.log
DUMP:
  SPACE: 15